apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    run: threetrees-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: threetrees-test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: threetrees-test
    spec:
      containers:
        - name: threetrees-container
          image: ghcr.io/3bases/3trees:0.5.0-beta.15
          ports:
            - containerPort: 1234
          resources:
            limits:
              memory: 2Gi
              cpu: '1'
            requests:
              memory: 1Gi
              cpu: '1'
